### ISSUE TITLE
"OpenGL4.4 is not supported" alert showed after running

### ISSUE THREAD

**Issue by looperrwang** [csyonghe/SpireMiniEngine#14]
Build success, once run, will show alert "OpenGL4.4 is not supported.". After clicking OK button, the program quits running. It seems to be related to my computer or windows version. What should I do to solve this problem?
![OpenGL4.4 is not supported](https://user-images.githubusercontent.com/43520554/61096873-a3fa2580-a48b-11e9-817a-2cce17c1dafd.png)

**Comment by csyonghe** [comment]
If you see this message, it means your graphics driver does not support OpenGL 4.4, which is required to run SpireMiniEngine.

Make sure you are using an NVIDIA/AMD GPU, or an Intel GPU that is at least HD Graphics 5xx series or later. If you are using an older Intel GPU, it will not work.
