### ISSUE TITLE
Error messages when building/running for the first time

### ISSUE THREAD

**Issue by tangent-vector** [csyonghe/SpireMiniEngine#2]
I don't know what the expected output is for the engine, but I see the following when I try to run it for the first time:

![image](https://cloud.githubusercontent.com/assets/10618364/20283336/69127122-aa6d-11e6-914e-ce8829eef57d.png)

I see a character and a ground plane, but the character is just the animation rig (a little walking skeleton) and not a mesh. I'm not sure if that is as expected.

**Comment by csyonghe** [comment]
The latest check-in should have fixed this issue.
